name: ahia

services:
  pg:
    image: postgres:18-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ahia
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql
    restart: unless-stopped

volumes:
  pgdata:
